DROP DATABASE IF EXISTS coinsx_test;
DROP DATABASE IF EXISTS coinsx;

CREATE DATABASE coinsx_test;
CREATE DATABASE coinsx;

\c coinsx

ALTER DATABASE coinsx OWNER TO jd;
ALTER DATABASE coinsx_test OWNER TO jd;
