-- 00001_foundation.sql — dedicated schema, types, identity & financial tables
-- Coins → self-hosted Supabase migration (plan §4.1, §4.2)
-- Additive, versioned. Safe to apply on the shared Supabase project: creates
-- only coins-owned objects. Never drops anything outside schema `coins`.

BEGIN;

CREATE SCHEMA IF NOT EXISTS coins;
COMMENT ON SCHEMA coins IS 'Coins trading simulator — isolated product schema on shared Supabase.';

-- ---------------------------------------------------------------------------
-- Types (plan §4.1)
-- ---------------------------------------------------------------------------
CREATE TYPE coins.trade_side AS ENUM ('BUY','SELL');
CREATE TYPE coins.market_cycle AS ENUM ('STRONG_BOOM','MILD_BOOM','STRONG_BUST','MILD_BUST','STABLE');
CREATE TYPE coins.candle_interval AS ENUM ('15m','1h','6h','1d');
CREATE TYPE coins.market_candle_interval AS ENUM ('1m','15m','1h','1d');

-- ---------------------------------------------------------------------------
-- updated_at trigger helper
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION coins.set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$;

-- ---------------------------------------------------------------------------
-- profiles (plan §4.2) — one row per Supabase Auth user who opts into Coins
-- ---------------------------------------------------------------------------
CREATE TABLE coins.profiles (
  id             uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE RESTRICT,
  legacy_user_id bigint UNIQUE,
  username       text NOT NULL,
  legacy_email   text,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  disabled_at    timestamptz,
  CONSTRAINT username_len CHECK (char_length(username) BETWEEN 1 AND 50)
);
-- case-insensitive uniqueness
CREATE UNIQUE INDEX profiles_username_lower_key ON coins.profiles (lower(username));
CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON coins.profiles
  FOR EACH ROW EXECUTE FUNCTION coins.set_updated_at();

-- ---------------------------------------------------------------------------
-- wallets — £ cash. numeric(20,2); bounded checks reject NaN/±Infinity
-- (PG treats NaN as greater than every number, so two-sided bounds reject it).
-- ---------------------------------------------------------------------------
CREATE TABLE coins.wallets (
  user_id      uuid PRIMARY KEY REFERENCES coins.profiles(id) ON DELETE RESTRICT,
  cash_balance numeric(20,2) NOT NULL DEFAULT 1000.00
               CHECK (cash_balance >= 0 AND cash_balance <= 1e15),
  version      bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER wallets_updated_at BEFORE UPDATE ON coins.wallets
  FOR EACH ROW EXECUTE FUNCTION coins.set_updated_at();

-- ---------------------------------------------------------------------------
-- legacy_identity_map — service-only; deterministic repeated imports
-- ---------------------------------------------------------------------------
CREATE TABLE coins.legacy_identity_map (
  legacy_user_id bigint PRIMARY KEY,
  auth_user_id   uuid UNIQUE NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  migration_batch text NOT NULL,
  status         text NOT NULL DEFAULT 'created'
                 CHECK (status IN ('created','reset_sent','activated')),
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER legacy_identity_map_updated_at BEFORE UPDATE ON coins.legacy_identity_map
  FOR EACH ROW EXECUTE FUNCTION coins.set_updated_at();

-- ---------------------------------------------------------------------------
-- balance_adjustments — immutable, service-only replacement for the unsafe
-- legacy funds route. Written only by a service-role RPC (Task: admin).
-- ---------------------------------------------------------------------------
CREATE TABLE coins.balance_adjustments (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          uuid NOT NULL REFERENCES coins.profiles(id) ON DELETE RESTRICT,
  amount           numeric(20,2) NOT NULL
                   CHECK (amount <> 0 AND abs(amount) <= 1e15
                          AND amount::text NOT IN ('NaN','Infinity','-Infinity')),
  balance_before   numeric(20,2) NOT NULL,
  balance_after    numeric(20,2) NOT NULL CHECK (balance_after >= 0 AND balance_after <= 1e15),
  reason           text NOT NULL CHECK (char_length(reason) BETWEEN 1 AND 500),
  actor            text NOT NULL,            -- e.g. 'service_role:migration' — never a token
  idempotency_key  uuid,
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, idempotency_key)
);

COMMIT;
