-- 00002_market_tables.sql — assets, holdings, trades ledger, market/history tables
-- Coins → self-hosted Supabase migration (plan §4.2, §4.3)

BEGIN;

-- ---------------------------------------------------------------------------
-- assets (legacy "coins") — public read, service-only write
-- ---------------------------------------------------------------------------
CREATE TABLE coins.assets (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_coin_id     bigint UNIQUE NOT NULL,
  name               varchar(50)  NOT NULL,
  symbol             varchar(10)  NOT NULL,
  current_price      numeric(24,8) NOT NULL
                     CHECK (current_price > 0 AND current_price <= 1e12),
  market_cap         numeric(30,2) NOT NULL CHECK (market_cap >= 0 AND market_cap <= 1e24),
  circulating_supply numeric(30,8) NOT NULL
                     CHECK (circulating_supply >= 0 AND circulating_supply <= 1e24),
  price_change_24h   numeric(12,6),
  founder            text,
  listed_at          timestamptz NOT NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX assets_symbol_upper_key ON coins.assets (upper(symbol));
CREATE TRIGGER assets_updated_at BEFORE UPDATE ON coins.assets
  FOR EACH ROW EXECUTE FUNCTION coins.set_updated_at();

-- ---------------------------------------------------------------------------
-- holdings — no direct client writes
-- ---------------------------------------------------------------------------
CREATE TABLE coins.holdings (
  user_id    uuid   NOT NULL REFERENCES coins.profiles(id) ON DELETE RESTRICT,
  asset_id   bigint NOT NULL REFERENCES coins.assets(id)   ON DELETE RESTRICT,
  quantity   numeric(30,12) NOT NULL DEFAULT 0 CHECK (quantity >= 0 AND quantity <= 1e18),
  cost_basis numeric(30,2)  NOT NULL DEFAULT 0 CHECK (cost_basis >= 0 AND cost_basis <= 1e15),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, asset_id)
);
CREATE TRIGGER holdings_updated_at BEFORE UPDATE ON coins.holdings
  FOR EACH ROW EXECUTE FUNCTION coins.set_updated_at();

-- ---------------------------------------------------------------------------
-- trades — immutable append-only ledger
-- ---------------------------------------------------------------------------
CREATE TABLE coins.trades (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_transaction_id  bigint UNIQUE,
  user_id                uuid NOT NULL REFERENCES coins.profiles(id) ON DELETE RESTRICT,
  asset_id               bigint NOT NULL REFERENCES coins.assets(id) ON DELETE RESTRICT,
  side                   coins.trade_side NOT NULL,
  quantity               numeric(30,12) NOT NULL CHECK (quantity > 0 AND quantity <= 1e18),
  unit_price             numeric(24,8)  NOT NULL CHECK (unit_price > 0 AND unit_price <= 1e12),
  total_amount           numeric(30,2)  NOT NULL CHECK (total_amount > 0 AND total_amount <= 1e15),
  idempotency_key        uuid,
  cash_balance_after     numeric(20,2),
  holding_quantity_after numeric(30,12),
  executed_at            timestamptz NOT NULL DEFAULT now(),
  source                 text NOT NULL DEFAULT 'supabase_rpc',
  CONSTRAINT trades_idempotency_unique UNIQUE (user_id, idempotency_key)
);
CREATE INDEX trades_user_time_idx  ON coins.trades (user_id, executed_at DESC, id DESC);
CREATE INDEX trades_asset_time_idx ON coins.trades (asset_id, executed_at DESC);

-- Immutability: reject UPDATE/DELETE. A tightly controlled migration context
-- may set coins.allow_ledger_mutation='on' in-session (service role only).
CREATE OR REPLACE FUNCTION coins.guard_trades_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF current_setting('coins.allow_ledger_mutation', true) IS DISTINCT FROM 'on' THEN
    RAISE EXCEPTION 'trades is an append-only ledger' USING ERRCODE = 'raise_exception';
  END IF;
  RETURN COALESCE(NEW, OLD);
END $$;
CREATE TRIGGER trades_immutable BEFORE UPDATE OR DELETE ON coins.trades
  FOR EACH ROW EXECUTE FUNCTION coins.guard_trades_immutable();
CREATE TRIGGER balance_adjustments_immutable BEFORE UPDATE OR DELETE ON coins.balance_adjustments
  FOR EACH ROW EXECUTE FUNCTION coins.guard_trades_immutable();

-- ---------------------------------------------------------------------------
-- market_state — singleton
-- ---------------------------------------------------------------------------
CREATE TABLE coins.market_state (
  id                  boolean PRIMARY KEY DEFAULT true CHECK (id),
  is_running          boolean NOT NULL DEFAULT false,
  cycle               coins.market_cycle NOT NULL DEFAULT 'STABLE',
  cycle_started_at    timestamptz NOT NULL DEFAULT now(),
  cycle_ends_at       timestamptz NOT NULL DEFAULT now(),
  tick_sequence       bigint NOT NULL DEFAULT 0 CHECK (tick_sequence >= 0),
  last_tick_at        timestamptz,
  worker_heartbeat_at timestamptz,
  worker_instance_id  text,
  halted_reason       text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);
INSERT INTO coins.market_state (id) VALUES (true) ON CONFLICT (id) DO NOTHING;
CREATE TRIGGER market_state_updated_at BEFORE UPDATE ON coins.market_state
  FOR EACH ROW EXECUTE FUNCTION coins.set_updated_at();

-- ---------------------------------------------------------------------------
-- asset_simulation_state — persists everything the legacy singleton kept in
-- process memory (plan §9.2)
-- ---------------------------------------------------------------------------
CREATE TABLE coins.asset_simulation_state (
  asset_id          bigint PRIMARY KEY REFERENCES coins.assets(id) ON DELETE RESTRICT,
  baseline_price    numeric(24,8) NOT NULL CHECK (baseline_price > 0 AND baseline_price <= 1e12),
  volatility        numeric(10,6) NOT NULL DEFAULT 0.01 CHECK (volatility >= 0 AND volatility <= 1),
  trend_direction   smallint NOT NULL DEFAULT 0 CHECK (trend_direction IN (-1,0,1)),
  trend_strength    numeric(10,6) NOT NULL DEFAULT 0 CHECK (trend_strength >= 0 AND trend_strength <= 1),
  trend_ends_at     timestamptz,
  event_type        text,
  event_multiplier  numeric(10,4),
  event_ends_at     timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER asset_simulation_state_updated_at BEFORE UPDATE ON coins.asset_simulation_state
  FOR EACH ROW EXECUTE FUNCTION coins.set_updated_at();

-- ---------------------------------------------------------------------------
-- price_ticks — raw 30 s history (worker/function writes only)
-- ---------------------------------------------------------------------------
CREATE TABLE coins.price_ticks (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_id      bigint NOT NULL REFERENCES coins.assets(id) ON DELETE RESTRICT,
  price         numeric(24,8) NOT NULL CHECK (price > 0 AND price <= 1e12),
  captured_at   timestamptz NOT NULL,
  tick_sequence bigint NOT NULL CHECK (tick_sequence > 0),
  source        text NOT NULL DEFAULT 'market_tick',
  UNIQUE (asset_id, tick_sequence)
);
CREATE INDEX price_ticks_asset_time_idx ON coins.price_ticks (asset_id, captured_at DESC) INCLUDE (price);

-- ---------------------------------------------------------------------------
-- price_candles — OHLC per asset/interval (plan §4.3)
-- ---------------------------------------------------------------------------
CREATE TABLE coins.price_candles (
  asset_id     bigint NOT NULL REFERENCES coins.assets(id) ON DELETE RESTRICT,
  interval     coins.candle_interval NOT NULL,
  bucket_start timestamptz NOT NULL,
  open   numeric(24,8) NOT NULL,
  high   numeric(24,8) NOT NULL,
  low    numeric(24,8) NOT NULL,
  close  numeric(24,8) NOT NULL,
  sample_count integer NOT NULL CHECK (sample_count > 0),
  is_complete boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (asset_id, interval, bucket_start),
  CONSTRAINT candle_ohlc_positive CHECK (open > 0 AND high > 0 AND low > 0 AND close > 0),
  CONSTRAINT candle_ohlc_consistent CHECK (
    high >= greatest(open, close, low) AND low <= least(open, close, high))
);
CREATE INDEX price_candles_lookup_idx ON coins.price_candles (asset_id, interval, bucket_start DESC);

-- ---------------------------------------------------------------------------
-- market_snapshots — aggregate quote index per tick (sum of current prices,
-- parity with legacy market_history; see plan §4.3 note on semantics)
-- ---------------------------------------------------------------------------
CREATE TABLE coins.market_snapshots (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tick_sequence bigint UNIQUE NOT NULL CHECK (tick_sequence > 0),
  total_value   numeric(30,8) NOT NULL CHECK (total_value >= 0 AND total_value <= 1e18),
  cycle         coins.market_cycle NOT NULL,
  captured_at   timestamptz NOT NULL
);
CREATE INDEX market_snapshots_time_idx ON coins.market_snapshots (captured_at DESC);

-- ---------------------------------------------------------------------------
-- market_candles — OHLC over the aggregate index
-- ---------------------------------------------------------------------------
CREATE TABLE coins.market_candles (
  interval     coins.market_candle_interval NOT NULL,
  bucket_start timestamptz NOT NULL,
  open   numeric(30,8) NOT NULL,
  high   numeric(30,8) NOT NULL,
  low    numeric(30,8) NOT NULL,
  close  numeric(30,8) NOT NULL,
  sample_count integer NOT NULL CHECK (sample_count > 0),
  is_complete boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (interval, bucket_start),
  CONSTRAINT market_candle_ohlc_nonneg CHECK (open >= 0 AND high >= 0 AND low >= 0 AND close >= 0),
  CONSTRAINT market_candle_ohlc_consistent CHECK (
    high >= greatest(open, close, low) AND low <= least(open, close, high))
);
CREATE INDEX market_candles_lookup_idx ON coins.market_candles (interval, bucket_start DESC);

-- ---------------------------------------------------------------------------
-- coin_statistics — imported ATH/ATL (plan §4.3)
-- ---------------------------------------------------------------------------
CREATE TABLE coins.coin_statistics (
  asset_id        bigint PRIMARY KEY REFERENCES coins.assets(id) ON DELETE RESTRICT,
  ath_price       numeric(24,8) CHECK (ath_price > 0 AND ath_price <= 1e12),
  ath_date        timestamptz,
  atl_price       numeric(24,8) CHECK (atl_price > 0 AND atl_price <= 1e12),
  atl_date        timestamptz,
  price_change_24h numeric(12,6),
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ath_gte_atl CHECK (ath_price IS NULL OR atl_price IS NULL OR ath_price >= atl_price)
);
CREATE TRIGGER coin_statistics_updated_at BEFORE UPDATE ON coins.coin_statistics
  FOR EACH ROW EXECUTE FUNCTION coins.set_updated_at();

COMMIT;
