-- 00008_migration_exceptions.sql — quarantine for legacy rows that cannot
-- satisfy target constraints (plan §7.3: report, never silently repair).
-- Service-only; no browser grants.

BEGIN;

CREATE TABLE coins.migration_exceptions (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_table text NOT NULL,
  legacy_id    bigint NOT NULL,
  payload      jsonb NOT NULL,
  reason       text NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (legacy_table, legacy_id)
);

ALTER TABLE coins.migration_exceptions ENABLE ROW LEVEL SECURITY;
-- no policies: deny-by-default for browser roles; service/migration only.

COMMENT ON TABLE coins.migration_exceptions IS
  'Legacy rows that violate target constraints, preserved verbatim for adjudication. Never auto-repaired.';

COMMIT;
