name: Deploy Backend API to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 213.165.91.221
          port: 4020
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Current directory before cd:"
            pwd
            cd /home/jd/back_coinsx
            echo "Current directory after cd:"
            pwd
            echo "Current git status:"
            git status
            echo "Fetching latest changes..."
            git fetch origin main
            echo "Resetting to origin/main..."
            git reset --hard origin/main
            echo "Installing dependencies..."
            npm install
            echo "Restarting PM2..."
            pm2 restart all
            echo "Deployment complete"
